# Generated by Django 5.2.6 on 2025-10-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTS_APP', '0002_manager_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='num_current_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manager',
            name='num_past_events',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manager',
            name='total_income',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='manager',
            name='total_tickets_sold',
            field=models.IntegerField(default=0),
        ),
    ]
