# Generated by Django 5.2.6 on 2025-10-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OTS_APP', '0003_alter_manager_num_current_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('user', 'User'), ('manager', 'Manager')], default='user', max_length=20),
        ),
    ]
