# Generated by Django 5.2.6 on 2025-11-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OTS_APP', '0005_event_creator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('user', 'event')},
        ),
    ]
